CREATE TABLE Personas (
    Id int IDENTITY(1,1) PRIMARY KEY,
	DNI int,
    Nombre varchar(255),
    Apellido varchar(255),
    Direccion varchar(255),
    FechaNacimiento DATE,
    Vigente int default 1
);
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (1, 'Buddie', 'Purves', '947 Independence Avenue', '13/04/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (2, 'Demeter', 'Paten', '29677 Crescent Oaks Parkway', '05/10/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (3, 'Fenelia', 'Gantley', '7 Bonner Terrace', '10/11/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (4, 'Clarita', 'Wallicker', '03 Elmside Crossing', '30/09/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (5, 'Elvin', 'Svanini', '5 Westend Pass', '19/01/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (6, 'Simonette', 'Pyatt', '93 Northland Trail', '07/09/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (7, 'Dennet', 'Bowser', '26587 Stuart Parkway', '17/08/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (8, 'Lewie', 'Kingsnod', '34862 Summerview Avenue', '20/06/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (9, 'Phylys', 'McVie', '3359 Victoria Pass', '18/10/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (10, 'Sileas', 'Corradengo', '5452 Lien Trail', '16/04/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (11, 'Gardy', 'Bilbrey', '2998 Bultman Drive', '25/04/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (12, 'Blinnie', 'Grimston', '29241 Armistice Hill', '17/01/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (13, 'Lenna', 'Attrey', '99964 High Crossing Plaza', '13/07/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (14, 'Beverie', 'Goodlett', '06607 Mallard Drive', '26/08/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (15, 'Sorcha', 'Tookill', '967 Drewry Pass', '20/10/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (16, 'Melinde', 'Sweetnam', '434 Darwin Place', '28/03/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (17, 'Charyl', 'Longmore', '76158 Bluejay Plaza', '27/02/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (18, 'Storm', 'Smalman', '84341 Mallard Parkway', '08/01/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (19, 'Guillaume', 'Heinreich', '718 Drewry Center', '13/02/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (20, 'Marget', 'Clutterham', '26 Tennessee Drive', '06/11/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (21, 'Ami', 'Ledgley', '200 Packers Crossing', '02/02/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (22, 'Syman', 'Manis', '296 Basil Crossing', '21/04/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (23, 'Giavani', 'Heazel', '7 Bunker Hill Lane', '18/06/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (24, 'Marietta', 'Luckman', '79061 Mesta Crossing', '13/07/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (25, 'Marjorie', 'Sellor', '76 Kennedy Place', '06/11/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (26, 'Abbot', 'Luis', '2263 Grim Road', '05/01/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (27, 'Sabrina', 'Gouley', '634 Ramsey Terrace', '21/07/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (28, 'Susannah', 'Clapson', '523 Clemons Lane', '24/08/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (29, 'Miran', 'Satyford', '46 Northfield Way', '26/10/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (30, 'Maggee', 'Dykins', '38 North Terrace', '23/09/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (31, 'Sumner', 'Aubrun', '78 Mifflin Place', '21/11/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (32, 'Ashlie', 'O''Cannan', '38 Packers Avenue', '02/06/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (33, 'Meriel', 'Phaup', '2915 Troy Terrace', '10/02/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (34, 'Emmit', 'Lorden', '35 Kinsman Road', '27/04/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (35, 'Diahann', 'Romanet', '96 Rigney Crossing', '18/02/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (36, 'Reiko', 'Wanell', '0 Lakewood Gardens Trail', '07/01/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (37, 'Annabella', 'Metts', '61757 Hooker Street', '14/04/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (38, 'Lily', 'Rockey', '5967 Mayfield Trail', '26/03/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (39, 'Dodie', 'Yglesia', '56607 Summer Ridge Junction', '16/09/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (40, 'Erika', 'Mangam', '683 1st Center', '18/01/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (41, 'Latisha', 'Meddick', '887 Anthes Avenue', '23/12/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (42, 'Holt', 'Ivanets', '3 Karstens Avenue', '19/10/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (43, 'Vilhelmina', 'Tranmer', '25689 Logan Park', '12/04/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (44, 'Joyan', 'Quartermain', '55777 Bunting Pass', '20/05/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (45, 'Huberto', 'Watkinson', '94 Packers Plaza', '08/10/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (46, 'Claudell', 'Lafuente', '48891 Corscot Plaza', '06/12/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (47, 'Shell', 'Vernalls', '0840 Talmadge Street', '24/05/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (48, 'Lolita', 'Ochterlonie', '16316 Artisan Way', '16/07/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (49, 'Gavra', 'Culp', '1508 Monterey Avenue', '01/02/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (50, 'Carlynn', 'Shalcros', '89622 Golf Course Place', '29/07/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (51, 'Pris', 'McKendo', '78 Pleasure Plaza', '20/03/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (52, 'Hayyim', 'Eagell', '35501 Moose Lane', '29/07/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (53, 'Ikey', 'Showl', '6392 Oakridge Street', '06/03/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (54, 'Sherrie', 'Prendeville', '29 Londonderry Road', '21/03/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (55, 'Marlene', 'Savidge', '71 Spenser Place', '15/03/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (56, 'Nicola', 'Doerffer', '39 Beilfuss Avenue', '26/06/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (57, 'Bord', 'Pearsey', '1 Sachs Road', '10/05/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (58, 'Norbie', 'Louch', '01 Schlimgen Court', '15/05/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (59, 'King', 'Cutteridge', '8260 Montana Court', '21/01/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (60, 'Binky', 'Farrand', '05155 Sunbrook Pass', '16/02/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (61, 'Levon', 'Denzey', '1 Springview Place', '06/01/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (62, 'Wilton', 'Wittey', '2141 Mandrake Park', '15/08/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (63, 'Rees', 'Delph', '8807 Express Circle', '17/07/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (64, 'Herby', 'Attwool', '8 Pankratz Road', '12/09/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (65, 'Granny', 'Medley', '2 Hooker Park', '27/03/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (66, 'Devland', 'Antonacci', '8 Meadow Vale Drive', '20/12/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (67, 'Pattie', 'Randerson', '44445 Carpenter Hill', '01/05/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (68, 'Janina', 'Issacson', '2841 Superior Parkway', '09/09/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (69, 'Rayna', 'Mc Ilwrick', '1397 Prentice Street', '28/05/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (70, 'Morgen', 'Goodered', '202 Portage Lane', '07/03/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (71, 'Dorothea', 'Insole', '5 Monica Road', '08/08/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (72, 'Margarete', 'Chick', '239 Division Pass', '23/04/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (73, 'Drucill', 'Doole', '82 Stoughton Crossing', '28/09/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (74, 'Georgeanne', 'O'' Driscoll', '92 Bashford Court', '05/07/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (75, 'Thorn', 'Fishbie', '290 Merry Pass', '04/04/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (76, 'Latisha', 'Zecchinelli', '7 David Point', '28/04/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (77, 'Amberly', 'Pettegree', '7835 Texas Drive', '16/05/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (78, 'Reina', 'Swalwel', '8416 Monterey Drive', '23/09/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (79, 'Leia', 'Larking', '07 Brickson Park Drive', '03/11/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (80, 'Egbert', 'Guiden', '43995 Magdeline Street', '13/03/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (81, 'Guinevere', 'Muress', '51836 Fairview Lane', '04/12/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (82, 'Kiri', 'Cuttle', '398 Vahlen Circle', '03/12/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (83, 'Kenneth', 'Deppe', '87799 Burning Wood Parkway', '10/04/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (84, 'Jerrie', 'Schukert', '760 Ludington Drive', '18/05/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (85, 'Honoria', 'Tregunna', '933 Bobwhite Crossing', '18/03/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (86, 'Annadiane', 'Clemmey', '15648 Blaine Drive', '25/05/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (87, 'Allix', 'Stanier', '908 Loomis Lane', '12/01/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (88, 'Claiborn', 'Fraine', '0 Lien Pass', '17/12/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (89, 'Rudd', 'Polland', '63 Atwood Drive', '18/11/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (90, 'Humphrey', 'Jerzycowski', '826 Laurel Place', '06/04/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (91, 'Reyna', 'MacBain', '21675 Eastwood Way', '20/04/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (92, 'Brittaney', 'Medendorp', '90214 Killdeer Parkway', '27/03/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (93, 'Diego', 'Snazel', '99 Brickson Park Way', '10/08/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (94, 'Brunhilde', 'Chang', '2685 Almo Junction', '03/12/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (95, 'Willy', 'Kynaston', '5096 Eggendart Alley', '21/09/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (96, 'Johnny', 'Diss', '329 Elka Trail', '30/07/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (97, 'Wynne', 'Rontree', '8 Kropf Lane', '27/10/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (98, 'Rosalind', 'Jurczik', '0497 Hermina Drive', '18/06/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (99, 'Mareah', 'Demeter', '75 Anderson Road', '29/01/1991');
insert into PERSONAS (DNI, Nombre, Apellido, Direccion, FechaNacimiento) values (100, 'Briggs', 'Lippett', '551 Briar Crest Hill', '15/10/1991');
